{% set version = "0.2.6" %}

package:
  name: sciunit
  version: {{ version }}

source:
  url: https://github.com/scidash/sciunit/archive/v{{ version }}.tar.gz
  sha256: 0163aa2b6345d9fc98e94e3f7e34eb564bc757d451632018df6632b261894707

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sciunit = sciunit.__main__:main

requirements:
  host:
    - setuptools
    - python >=3.6
    - pip
  run:
    - git
    - quantities
    - pandas
    - ipython
    - matplotlib-base
    - bs4
    - lxml
    - nbconvert
    - ipykernel
    - nbformat
    - gitpython
    - cerberus >=1.2
    - importlib-metadata
    - python >=3.6

test:
  imports:
    - sciunit
    - sciunit.unit_test

about:
  home: http://sciunit.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A test-driven framework for formally validating scientific models against data.
  description: |
    SciUnit is a discipline-agnostic framework for model validation, 
    handling all of the testing workflow by using a implementation-independent 
    interface to models. SciUnit also contains code for visualization 
    of model results, and command line tools for incorporating 
    testing into continuous integration workflows.
  doc_url: https://sciunit.readthedocs.io/
  dev_url: https://github.com/scidash/sciunit

extra:
  recipe-maintainers:
    - rgerkin
